language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls nose
  - python cltk_install.py

# command to run tests
script:
  - nosetests ./tests --with-coverage --cover-package=flask_pie --cover-xml --verbose --nologcapture
after_success:
  - coverage combine
  - coveralls